### ISSUE TITLE
SPI 25XX 

### ISSUE THREAD

**Issue by chonero** [bigbigmdm/QT-CH341A-LINUX-PROGRAMMER#1]
You could incorporate it for reading and writing of the spi 25xx flash.

**Comment by bigbigmdm** [comment]
Hello! I have not used this software for EEPROm SPI flash ICs.  For SPI flash programming I use Flashrom (https://www.flashrom.org) or the universal programmer SNANDer (https://github.com/bigbigmdm/SNANDer).

**Comment by bigbigmdm** [comment]
You can use my latest CH341A project: [IMSProg](https://github.com/bigbigmdm/IMSProg). It supports 25xxx, 24xxx, 45xxx, 93xxx series chips.
