### ISSUE TITLE
Dark theme, color scheme support

### ISSUE THREAD

**Issue by blackPantherOS** [bigbigmdm/QT-CH341A-LINUX-PROGRAMMER#6]
Hi, I love it your work, very useful and has fill a big void in all linux distro. Thank you!
If you have a small time, please add dark theme support as well for HEX viewer . 
RGDS

![ch341a:_programmer](https://github.com/bigbigmdm/QT-CH341A-LINUX-PROGRAMMER/assets/12883566/f1602050-a0b6-428e-a7e2-656497f20204)

**Comment by bigbigmdm** [comment]
Yeah. It's a mistake. I plan to fix it. Please use my universal programmer version - [IMSProg](https://github.com/bigbigmdm/IMSProg). It displays normally in both light and dark versions and supports many more chip models than QT-CH341A-LINUX-PROGRAMMER.

![en_dark2](https://github.com/bigbigmdm/QT-CH341A-LINUX-PROGRAMMER/assets/75389103/0199c437-8231-4182-b26b-a6a0989eb41b)


![en_dark](https://github.com/bigbigmdm/QT-CH341A-LINUX-PROGRAMMER/assets/75389103/b87bee8c-e5c4-4278-8300-c367af34a506)

**Comment by bigbigmdm** [comment]
![изображение](https://github.com/bigbigmdm/QT-CH341A-LINUX-PROGRAMMER/assets/75389103/c3dcaee3-776a-4f4c-8a31-efea9d08dd34)

**Comment by blackPantherOS** [comment]
> Yeah. It's a mistake. I plan to fix it. Please use my universal programmer version - [IMSProg](https://github.com/bigbigmdm/IMSProg). It displays normally in both light and dark versions and supports many more chip models than QT-CH341A-LINUX-PROGRAMMER. ![rus_dark](https://user-images.githubusercontent.com/75389103/282286264-cca7ea07-c180-4b4e-84cf-2d250769835d.png)

Yes! Yesterday I followed your github URL from the our old database and got to your old github repository. I didn't look around ..... but I just noticed that the software set has been expanded, very good, thanks :)
I build already and very good look and feel.

**Comment by bigbigmdm** [comment]
If you want to do the build yourself, please use the experimental branch [IMSProg_with_Debian_poilcy](https://github.com/bigbigmdm/IMSProg/tree/IMSProg_with_Debian_poilcy).

**Comment by bigbigmdm** [comment]
If you translate the files [editor/language](https://github.com/bigbigmdm/IMSProg/tree/IMSProg_with_Debian_poilcy/IMSProg_editor/language)
 and [programmer/language](https://github.com/bigbigmdm/IMSProg/tree/IMSProg_with_Debian_poilcy/IMSProg_programmer/language)
 to your native language - I'll be happy!

**Comment by bigbigmdm** [comment]
Thanks for a very nice translation of IMSProg!
