### ISSUE TITLE
README.md BUILDING instructions are incorrect

### ISSUE THREAD

**Issue by jalapenopuzzle** [bigbigmdm/QT-CH341A-LINUX-PROGRAMMER#7]
README.md BUILDING instructions are incorrect.
1. Download of ThirdParty software is not documented. I just cloned the respective repositories into the existing directories inside the ThirdParty directory.
2. It is not necessary to leave the build directory before running make. Doing so produces the following error:
user@host:~/QT-CH341A-LINUX-PROGRAMMER$ make -j4
make: *** No targets specified and no makefile found.  Stop.

```
mkdir build
cd build
cmake ..
**cd .. <- REMOVE**
make -j4
sudo make install
```

**Comment by bigbigmdm** [comment]
[jalapenopuzzle](https://github.com/jalapenopuzzle), thank you! 
While I'm fixing this you can check out my more versatile [IMSProg](https://github.com/bigbigmdm/IMSProg) programm.

**Comment by bigbigmdm** [comment]
Ok. I fixed it.
